export * from './types.js';
export * from './vector-search.js';
export { keywordSearch } from './keyword-search.js';
export { graphSearch, tokenizeQuery } from './graph-traversal.js';
export type { GraphSearchConfig } from './graph-traversal.js';
export { matchTriggers, evaluateCondition, cosineSimilarity } from './trigger-matcher.js';
export { scoreSalience, type SalienceConfig } from './salience-scorer.js';
export { fuseAndRank, type FusionResult } from './fusion.js';
export { surfaceContradictions, buildTimeline } from './contradiction-surfacer.js';
export { search, type SearchConfig } from './search.js';
export { compoundSearchSignal } from './compound-search.js';
export { CachedEmbeddingAdapter } from './embedding-cache.js';
