import { z } from 'zod';
export declare const ExtractionSchema: z.ZodObject<{
    id: z.ZodString;
    tenantId: z.ZodString;
    status: z.ZodEnum<["queued", "processing", "completed", "failed", "deduped"]>;
    inputType: z.ZodEnum<["conversation", "document", "url", "raw_text", "image", "audio", "code"]>;
    inputData: z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    inputHash: z.ZodString;
    inputSize: z.ZodNullable<z.ZodNumber>;
    scope: z.ZodEnum<["user", "agent", "session", "hive"]>;
    scopeId: z.ZodString;
    sessionId: z.ZodNullable<z.ZodString>;
    tierUsed: z.ZodNullable<z.ZodEnum<["heuristic", "cheap_llm", "smart_llm", "multi_tier"]>>;
    llmModel: z.ZodNullable<z.ZodString>;
    factsCreated: z.ZodNumber;
    factsUpdated: z.ZodNumber;
    factsInvalidated: z.ZodNumber;
    entitiesCreated: z.ZodNumber;
    edgesCreated: z.ZodNumber;
    costTokensInput: z.ZodNumber;
    costTokensOutput: z.ZodNumber;
    costUsd: z.ZodNumber;
    durationMs: z.ZodNullable<z.ZodNumber>;
    error: z.ZodNullable<z.ZodString>;
    retryCount: z.ZodNumber;
    createdAt: z.ZodDate;
    completedAt: z.ZodNullable<z.ZodDate>;
}, "strip", z.ZodTypeAny, {
    status: "queued" | "processing" | "completed" | "failed" | "deduped";
    id: string;
    tenantId: string;
    scope: "user" | "agent" | "session" | "hive";
    scopeId: string;
    sessionId: string | null;
    createdAt: Date;
    inputType: "code" | "conversation" | "document" | "url" | "raw_text" | "image" | "audio";
    inputData: string | Record<string, unknown> | null;
    inputHash: string;
    inputSize: number | null;
    tierUsed: "heuristic" | "cheap_llm" | "smart_llm" | "multi_tier" | null;
    llmModel: string | null;
    factsCreated: number;
    factsUpdated: number;
    factsInvalidated: number;
    entitiesCreated: number;
    edgesCreated: number;
    costTokensInput: number;
    costTokensOutput: number;
    costUsd: number;
    durationMs: number | null;
    error: string | null;
    retryCount: number;
    completedAt: Date | null;
}, {
    status: "queued" | "processing" | "completed" | "failed" | "deduped";
    id: string;
    tenantId: string;
    scope: "user" | "agent" | "session" | "hive";
    scopeId: string;
    sessionId: string | null;
    createdAt: Date;
    inputType: "code" | "conversation" | "document" | "url" | "raw_text" | "image" | "audio";
    inputData: string | Record<string, unknown> | null;
    inputHash: string;
    inputSize: number | null;
    tierUsed: "heuristic" | "cheap_llm" | "smart_llm" | "multi_tier" | null;
    llmModel: string | null;
    factsCreated: number;
    factsUpdated: number;
    factsInvalidated: number;
    entitiesCreated: number;
    edgesCreated: number;
    costTokensInput: number;
    costTokensOutput: number;
    costUsd: number;
    durationMs: number | null;
    error: string | null;
    retryCount: number;
    completedAt: Date | null;
}>;
export type Extraction = z.infer<typeof ExtractionSchema>;
export declare const CreateExtractionSchema: z.ZodObject<{
    tenantId: z.ZodString;
    inputType: z.ZodEnum<["conversation", "document", "url", "raw_text", "image", "audio", "code"]>;
    inputData: z.ZodString;
    inputHash: z.ZodString;
    inputSize: z.ZodOptional<z.ZodNumber>;
    scope: z.ZodEnum<["user", "agent", "session", "hive"]>;
    scopeId: z.ZodString;
    sessionId: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    tenantId: string;
    scope: "user" | "agent" | "session" | "hive";
    scopeId: string;
    inputType: "code" | "conversation" | "document" | "url" | "raw_text" | "image" | "audio";
    inputData: string;
    inputHash: string;
    sessionId?: string | undefined;
    inputSize?: number | undefined;
}, {
    tenantId: string;
    scope: "user" | "agent" | "session" | "hive";
    scopeId: string;
    inputType: "code" | "conversation" | "document" | "url" | "raw_text" | "image" | "audio";
    inputData: string;
    inputHash: string;
    sessionId?: string | undefined;
    inputSize?: number | undefined;
}>;
export type CreateExtraction = z.infer<typeof CreateExtractionSchema>;
//# sourceMappingURL=extraction.d.ts.map