import { z } from 'zod';
export declare const FactSchema: z.ZodObject<{
    id: z.ZodString;
    tenantId: z.ZodString;
    scope: z.ZodEnum<["user", "agent", "session", "hive"]>;
    scopeId: z.ZodString;
    sessionId: z.ZodNullable<z.ZodString>;
    content: z.ZodString;
    embeddingModel: z.ZodNullable<z.ZodString>;
    embeddingDim: z.ZodNullable<z.ZodNumber>;
    version: z.ZodNumber;
    lineageId: z.ZodString;
    validFrom: z.ZodDate;
    validUntil: z.ZodNullable<z.ZodDate>;
    operation: z.ZodEnum<["create", "update", "invalidate"]>;
    parentId: z.ZodNullable<z.ZodString>;
    importance: z.ZodNumber;
    frequency: z.ZodNumber;
    lastAccessed: z.ZodNullable<z.ZodDate>;
    decayScore: z.ZodNumber;
    contradictionStatus: z.ZodEnum<["none", "active", "resolved", "superseded"]>;
    contradictsId: z.ZodNullable<z.ZodString>;
    sourceType: z.ZodEnum<["conversation", "document", "url", "raw_text", "api", "agent_self"]>;
    sourceRef: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    confidence: z.ZodNumber;
    originalContent: z.ZodNullable<z.ZodString>;
    extractionId: z.ZodNullable<z.ZodString>;
    extractionTier: z.ZodNullable<z.ZodEnum<["heuristic", "cheap_llm", "smart_llm"]>>;
    modality: z.ZodEnum<["text", "image", "audio", "code", "document"]>;
    tags: z.ZodArray<z.ZodString, "many">;
    metadata: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    /** When the event described in the fact actually occurred */
    eventDate: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
    /** When the conversation/document was authored */
    documentDate: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
    /** The original conversation chunk this fact was extracted from */
    sourceChunk: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    embeddingModel: string | null;
    embeddingDim: number | null;
    id: string;
    tenantId: string;
    scope: "user" | "agent" | "session" | "hive";
    scopeId: string;
    sessionId: string | null;
    content: string;
    version: number;
    lineageId: string;
    validFrom: Date;
    validUntil: Date | null;
    operation: "create" | "update" | "invalidate";
    parentId: string | null;
    importance: number;
    frequency: number;
    lastAccessed: Date | null;
    decayScore: number;
    contradictionStatus: "none" | "active" | "resolved" | "superseded";
    contradictsId: string | null;
    sourceType: "conversation" | "document" | "url" | "raw_text" | "api" | "agent_self";
    sourceRef: Record<string, unknown> | null;
    confidence: number;
    originalContent: string | null;
    extractionId: string | null;
    extractionTier: "heuristic" | "cheap_llm" | "smart_llm" | null;
    modality: "code" | "document" | "text" | "image" | "audio";
    tags: string[];
    metadata: Record<string, unknown>;
    sourceChunk: string | null;
    createdAt: Date;
    eventDate?: Date | null | undefined;
    documentDate?: Date | null | undefined;
}, {
    embeddingModel: string | null;
    embeddingDim: number | null;
    id: string;
    tenantId: string;
    scope: "user" | "agent" | "session" | "hive";
    scopeId: string;
    sessionId: string | null;
    content: string;
    version: number;
    lineageId: string;
    validFrom: Date;
    validUntil: Date | null;
    operation: "create" | "update" | "invalidate";
    parentId: string | null;
    importance: number;
    frequency: number;
    lastAccessed: Date | null;
    decayScore: number;
    contradictionStatus: "none" | "active" | "resolved" | "superseded";
    contradictsId: string | null;
    sourceType: "conversation" | "document" | "url" | "raw_text" | "api" | "agent_self";
    sourceRef: Record<string, unknown> | null;
    confidence: number;
    originalContent: string | null;
    extractionId: string | null;
    extractionTier: "heuristic" | "cheap_llm" | "smart_llm" | null;
    modality: "code" | "document" | "text" | "image" | "audio";
    tags: string[];
    metadata: Record<string, unknown>;
    createdAt: Date;
    eventDate?: Date | null | undefined;
    documentDate?: Date | null | undefined;
    sourceChunk?: string | null | undefined;
}>;
export type Fact = z.infer<typeof FactSchema>;
export declare const CreateFactSchema: z.ZodObject<{
    tenantId: z.ZodString;
    scope: z.ZodEnum<["user", "agent", "session", "hive"]>;
    scopeId: z.ZodString;
    sessionId: z.ZodOptional<z.ZodString>;
    content: z.ZodString;
    embeddingModel: z.ZodOptional<z.ZodString>;
    embeddingDim: z.ZodOptional<z.ZodNumber>;
    lineageId: z.ZodOptional<z.ZodString>;
    parentId: z.ZodOptional<z.ZodString>;
    importance: z.ZodDefault<z.ZodNumber>;
    confidence: z.ZodDefault<z.ZodNumber>;
    operation: z.ZodDefault<z.ZodEnum<["create", "update", "invalidate"]>>;
    contradictionStatus: z.ZodDefault<z.ZodEnum<["none", "active", "resolved", "superseded"]>>;
    contradictsId: z.ZodOptional<z.ZodString>;
    sourceType: z.ZodOptional<z.ZodEnum<["conversation", "document", "url", "raw_text", "api", "agent_self"]>>;
    sourceRef: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    originalContent: z.ZodOptional<z.ZodString>;
    extractionId: z.ZodOptional<z.ZodString>;
    extractionTier: z.ZodOptional<z.ZodEnum<["heuristic", "cheap_llm", "smart_llm"]>>;
    modality: z.ZodDefault<z.ZodEnum<["text", "image", "audio", "code", "document"]>>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    sourceChunk: z.ZodOptional<z.ZodString>;
    /** When the event described in the fact actually occurred */
    eventDate: z.ZodOptional<z.ZodDate>;
    /** When the conversation/document was authored */
    documentDate: z.ZodOptional<z.ZodDate>;
}, "strip", z.ZodTypeAny, {
    tenantId: string;
    scope: "user" | "agent" | "session" | "hive";
    scopeId: string;
    content: string;
    operation: "create" | "update" | "invalidate";
    importance: number;
    contradictionStatus: "none" | "active" | "resolved" | "superseded";
    confidence: number;
    modality: "code" | "document" | "text" | "image" | "audio";
    tags: string[];
    metadata: Record<string, unknown>;
    embeddingModel?: string | undefined;
    embeddingDim?: number | undefined;
    sessionId?: string | undefined;
    lineageId?: string | undefined;
    parentId?: string | undefined;
    contradictsId?: string | undefined;
    sourceType?: "conversation" | "document" | "url" | "raw_text" | "api" | "agent_self" | undefined;
    sourceRef?: Record<string, unknown> | undefined;
    originalContent?: string | undefined;
    extractionId?: string | undefined;
    extractionTier?: "heuristic" | "cheap_llm" | "smart_llm" | undefined;
    eventDate?: Date | undefined;
    documentDate?: Date | undefined;
    sourceChunk?: string | undefined;
}, {
    tenantId: string;
    scope: "user" | "agent" | "session" | "hive";
    scopeId: string;
    content: string;
    embeddingModel?: string | undefined;
    embeddingDim?: number | undefined;
    sessionId?: string | undefined;
    lineageId?: string | undefined;
    operation?: "create" | "update" | "invalidate" | undefined;
    parentId?: string | undefined;
    importance?: number | undefined;
    contradictionStatus?: "none" | "active" | "resolved" | "superseded" | undefined;
    contradictsId?: string | undefined;
    sourceType?: "conversation" | "document" | "url" | "raw_text" | "api" | "agent_self" | undefined;
    sourceRef?: Record<string, unknown> | undefined;
    confidence?: number | undefined;
    originalContent?: string | undefined;
    extractionId?: string | undefined;
    extractionTier?: "heuristic" | "cheap_llm" | "smart_llm" | undefined;
    modality?: "code" | "document" | "text" | "image" | "audio" | undefined;
    tags?: string[] | undefined;
    metadata?: Record<string, unknown> | undefined;
    eventDate?: Date | undefined;
    documentDate?: Date | undefined;
    sourceChunk?: string | undefined;
}>;
export type CreateFact = z.infer<typeof CreateFactSchema>;
//# sourceMappingURL=fact.d.ts.map