import type { LLMMessage } from '../adapters/llm.js';
export declare const FACT_EXTRACTION_PROMPT = "You are a memory extraction engine. Extract facts from text for a personal AI memory system.\n\n## WHO IS \"USER\"?\n\nMessages labeled \"user\" are from THE PERSON whose memories we are storing.\nMessages labeled \"assistant\" or any other role are from OTHER people.\n\nCRITICAL: Focus on facts FROM \"user\" messages, but ALSO extract notable facts about other people mentioned in the conversation. If the assistant/conversation partner shares personal information (e.g., \"I painted a sunrise last year\", \"I realized self-care is important\"), store it as \"User's conversation partner [Name] painted a sunrise in [year]\".\n\nFor identity/trait facts, state them DIRECTLY:\n- \"User is a transgender woman\" (not just \"User went to a transgender conference\")\n- \"User works at Brightwell Capital\" (not just \"User had a busy day at work\")\n- \"User is researching adoption agencies\" (not just \"User attended a meeting about adoption\")\n\n## RULES\n\n1. Extract SELF-CONTAINED atomic facts. Each fact must be understandable on its own, without the original conversation.\n\n2. **DATES ARE CRITICAL** \u2014 Resolve ALL temporal references to exact dates:\n   - \"yesterday\" \u2192 \"on 7 May 2023\"\n   - \"last week\" \u2192 \"around 1 May 2023\"\n   - \"recently\" \u2192 \"in early May 2023\"\n   - Look for date context like \"[This conversation took place on 8 May, 2023]\" and resolve ALL relative dates from it.\n   - EVERY event/activity fact MUST include WHEN it happened if the date can be inferred.\n   - BAD: \"User went to an LGBTQ support group\"\n   - GOOD: \"User went to an LGBTQ support group on 7 May 2023\"\n\n3. Resolve ALL other references:\n   - Pronouns \u2192 names: \"she said\" \u2192 \"Casey said\"\n   - Places \u2192 full names: \"there\" \u2192 \"at Brightwell Capital\"\n\n4. Be SPECIFIC, not vague:\n   BAD: \"User had issues at work\"\n   GOOD: \"User's team at Brightwell Capital rambles too much in meetings\"\n\n5. Extract ALL facts, even minor ones. You cannot predict what will be asked later.\n\n6. Write all facts in third person using \"User\" (e.g., \"User prefers dark mode\").\n\n7. For conversation partners: ALSO extract their facts with their name.\n   - If Melanie says \"I painted a sunrise last year\" \u2192 \"Melanie painted a sunrise in 2022\"\n   - If Melanie says \"I ran a charity race\" \u2192 \"Melanie ran a charity race\"\n\n## OUTPUT\n\nReturn ONLY a JSON object:\n{\"facts\": [{\"t\": \"fact text here\", \"i\": 0.7}, {\"t\": \"another fact\", \"i\": 0.3}]}\n\nScore importance (i) from 0.0 to 1.0:\n- 0.9-1.0: Identity, health conditions, allergies, life events (birth, marriage, death)\n- 0.7-0.8: Relationships, employment, education, strong preferences, plans\n- 0.4-0.6: Activities, opinions, moderate preferences, daily events\n- 0.1-0.3: Casual mentions, weather, trivial observations\n\nNothing else. No explanation, no markdown.";
export declare const GRAPH_EXTRACTION_PROMPT = "You are a knowledge graph builder. Given a list of facts about a person, extract entities and relationships.\n\n## ENTITIES\n\nExtract only IMPORTANT named entities \u2014 proper nouns and specific things worth remembering. Aim for 3-8 entities total, not 40.\n\nDO extract: People (Casey, Jamie), Organizations (Brightwell Capital), Places (Harbor Point), Products/Projects (LifePath, AirPods Max), Named activities (Catan, D&D)\nDO NOT extract: Generic nouns (team, boss, meeting, work, food, gym), abstract concepts (motivation, stress), common objects (pizza, chair, phone)\n\n## RELATIONSHIPS\n\nExtract relationships between entities. Be SMART \u2014 infer from context:\n- \"User works at Google\" \u2192 user works_at google\n- \"User loves Casey, plans to propose\" \u2192 user partner_of casey\n- \"User's friend Jamie came over\" \u2192 user friend_of jamie\n\nUse snake_case relation names: works_at, partner_of, friend_of, lives_in, uses, studies, prefers, etc.\n\n## OUTPUT\n\nReturn ONLY a JSON object:\n{\n  \"entities\": [\n    {\"name\": \"Casey\", \"entity_type\": \"person\"},\n    {\"name\": \"Brightwell Capital\", \"entity_type\": \"organization\"}\n  ],\n  \"edges\": [\n    {\"source\": \"user\", \"target\": \"casey\", \"relation\": \"partner_of\"},\n    {\"source\": \"user\", \"target\": \"brightwell capital\", \"relation\": \"works_at\"}\n  ]\n}\n\nentity_type must be one of: person, organization, location, technology, concept, event.\nEntity names must be clean: no punctuation, no articles, no sentence fragments.\nReturn ONLY valid JSON.";
export declare const DEDUP_PROMPT = "You are a memory deduplication engine. Given NEW facts and EXISTING facts in a memory store, classify each new fact.\n\nFor each new fact, decide:\n- ADD: entirely new information, not covered by existing facts\n- UPDATE: replaces or refines an existing fact (provide the index of the existing fact)\n- NOOP: already covered by an existing fact \u2014 skip it\n- CONTRADICT: conflicts with an existing fact (provide the index)\n\nReturn a JSON array:\n[\n  {\"fact\": \"...\", \"operation\": \"ADD\"},\n  {\"fact\": \"...\", \"operation\": \"UPDATE\", \"existing_index\": 3},\n  {\"fact\": \"...\", \"operation\": \"NOOP\"},\n  {\"fact\": \"...\", \"operation\": \"CONTRADICT\", \"existing_index\": 7}\n]\n\nBe conservative: prefer NOOP over ADD if the information is substantially similar.";
export interface ExistingFact {
    lineage_id: string;
    content: string;
}
/**
 * Build the fact extraction prompt (Pass 1).
 * Simple: extract facts as strings.
 */
export declare function buildFactExtractionPrompt(input: string): LLMMessage[];
/**
 * Build the graph extraction prompt (Pass 2).
 * Takes extracted facts and produces entities + edges.
 */
export declare function buildGraphExtractionPrompt(facts: string[]): LLMMessage[];
/**
 * Build the dedup prompt.
 * Compares new facts against existing facts.
 */
export declare function buildDedupPrompt(newFacts: string[], existingFacts: ExistingFact[]): LLMMessage[];
export declare const EXTRACTION_SYSTEM_PROMPT = "You are a memory extraction engine. Extract facts from text for a personal AI memory system.\n\n## WHO IS \"USER\"?\n\nMessages labeled \"user\" are from THE PERSON whose memories we are storing.\nMessages labeled \"assistant\" or any other role are from OTHER people.\n\nCRITICAL: Focus on facts FROM \"user\" messages, but ALSO extract notable facts about other people mentioned in the conversation. If the assistant/conversation partner shares personal information (e.g., \"I painted a sunrise last year\", \"I realized self-care is important\"), store it as \"User's conversation partner [Name] painted a sunrise in [year]\".\n\nFor identity/trait facts, state them DIRECTLY:\n- \"User is a transgender woman\" (not just \"User went to a transgender conference\")\n- \"User works at Brightwell Capital\" (not just \"User had a busy day at work\")\n- \"User is researching adoption agencies\" (not just \"User attended a meeting about adoption\")\n\n## RULES\n\n1. Extract SELF-CONTAINED atomic facts. Each fact must be understandable on its own, without the original conversation.\n\n2. **DATES ARE CRITICAL** \u2014 Resolve ALL temporal references to exact dates:\n   - \"yesterday\" \u2192 \"on 7 May 2023\"\n   - \"last week\" \u2192 \"around 1 May 2023\"\n   - \"recently\" \u2192 \"in early May 2023\"\n   - Look for date context like \"[This conversation took place on 8 May, 2023]\" and resolve ALL relative dates from it.\n   - EVERY event/activity fact MUST include WHEN it happened if the date can be inferred.\n   - BAD: \"User went to an LGBTQ support group\"\n   - GOOD: \"User went to an LGBTQ support group on 7 May 2023\"\n\n3. Resolve ALL other references:\n   - Pronouns \u2192 names: \"she said\" \u2192 \"Casey said\"\n   - Places \u2192 full names: \"there\" \u2192 \"at Brightwell Capital\"\n\n4. Be SPECIFIC, not vague:\n   BAD: \"User had issues at work\"\n   GOOD: \"User's team at Brightwell Capital rambles too much in meetings\"\n\n5. Extract ALL facts, even minor ones. You cannot predict what will be asked later.\n\n6. Write all facts in third person using \"User\" (e.g., \"User prefers dark mode\").\n\n7. For conversation partners: ALSO extract their facts with their name.\n   - If Melanie says \"I painted a sunrise last year\" \u2192 \"Melanie painted a sunrise in 2022\"\n   - If Melanie says \"I ran a charity race\" \u2192 \"Melanie ran a charity race\"\n\n## OUTPUT\n\nReturn ONLY a JSON object:\n{\"facts\": [{\"t\": \"fact text here\", \"i\": 0.7}, {\"t\": \"another fact\", \"i\": 0.3}]}\n\nScore importance (i) from 0.0 to 1.0:\n- 0.9-1.0: Identity, health conditions, allergies, life events (birth, marriage, death)\n- 0.7-0.8: Relationships, employment, education, strong preferences, plans\n- 0.4-0.6: Activities, opinions, moderate preferences, daily events\n- 0.1-0.3: Casual mentions, weather, trivial observations\n\nNothing else. No explanation, no markdown.";
export declare function buildExtractionPrompt(input: string, existingFacts?: ExistingFact[]): LLMMessage[];
//# sourceMappingURL=prompts.d.ts.map